#!/usr/bin/python

import struct
import binascii

class AC2Exception(Exception):
      pass

class AC2DataFile:
      """A simple class to allow data replacement in Asheron's Call 2 data files."""

      def __init__(self, filename):
          self.fileHandle = open(filename, "rb")
          print self.fileHandle
          self.fileHandle.seek(0x12c)
          buf = self.fileHandle.read(4*9)
          #print "read buf:", binascii.hexlify(buf)
          magic, blockSize, fileSize, contentType, contentSubtype, firstFreeBlock, lastFreeBlock, freeBlockCount, rootOffset = struct.unpack("<IIIIIIIII", buf);
          if magic != 0x00005442:
             raise AC2Exception("Bad magic number for an AC2 data file")
          self.blockSize      = blockSize
          self.contentType    = contentType
          self.contentSubtype = contentSubtype
          self.firstFreeBlock = firstFreeBlock
          self.lastFreeBlock  = lastFreeBlock
          self.freeBlockCount = freeBlockCount
          self.rootOffset     = rootOffset

      def __str__(self):
          return "file: %s, blockSize: %u, contentType: %08x, contentSubtype: %08x, firstFreeBlock: %08x, lastFreeBlock: %08x, freeBlockCount: %u, rootOffset: %08x" % (self.fileHandle.name, self.blockSize, self.contentType, self.contentSubtype, self.firstFreeBlock, self.lastFreeBlock, self.freeBlockCount, self.rootOffset)

df = AC2DataFile("mod/portal.dat")
print df
